version: '3'

services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"  # Expose NodeJS app's port

  nginx:
    image: nginx
    ports:
      - "8080:80"  # Expose NGINX port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom NGINX configuration
    depends_on:
      - nodejs-app
      